blank_issues_enabled: false
contact_links:
  - name: 💬 Matrix
    url: https://matrix.to/#/#voxkb:matrix.org
    about: General chat about VoxKB and quick Q/A
  - name: ❓ Questions / Feedback
    url: https://github.com/voxkb/voxkb/discussions/new/choose
    about: Post your questions or feedback in the discussions panel
